In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
os.chdir(r"C:\Users\A_PORTEU\python_projects\lib_climate_alignment")

In [72]:
first_year_available, last_year_available = 2019, 2024

df = pd.read_parquet(
    f"data/intermediate_data/df_merged_all_infos_{first_year_available}_{last_year_available}.parquet"
)
df_hist_trends = pd.read_csv(
    "data/intermediate_data/region_sector_historical_trends.csv"
)
df_emissions_adjusted = pd.read_csv(
    f"data/intermediate_data/df_emissions_rate_adjusted_{first_year_available}_{last_year_available}.csv"
)

# ----------------------------
# Parameters
# ----------------------------
regions = list(df["region_0"].unique())
list_high_impact_sector = list(df["high_impact_sector"].dropna().sort_values().unique())
trend_years_interval_col = "average_trend_2014_2024"
delta_years_str = [
    f"{int(y)}-{y+1}" for y in range(first_year_available, last_year_available)
]

# ----------------------------
# Find aligned equities
# ----------------------------
df_eq_emissions_adjusted = pd.merge(
    df[["isin", "region_0", "high_impact_sector"]].drop_duplicates(),
    df_emissions_adjusted,
    on="isin",
    how="right",
)
df_eq_emissions_adjusted = pd.merge(
    df_eq_emissions_adjusted,
    df_hist_trends.rename(columns={"region": "region_0"}),
    on=["region_0", "high_impact_sector"],
    how="left",
)
df_eq_emissions_adjusted["average_rate"] = df_eq_emissions_adjusted[
    delta_years_str
].mean(axis=1)
df_eq_emissions_adjusted["is_average_rate_below_trend"] = (
    df_eq_emissions_adjusted["average_rate"]
    <= df_eq_emissions_adjusted[trend_years_interval_col]
)

# ----------------------------
# Final table
# ----------------------------

nbr_eq_below_trend = (
    df_eq_emissions_adjusted.groupby(["region_0", "high_impact_sector"])[
        "is_average_rate_below_trend"
    ]
    .sum()
    .reset_index()
    .pivot(
        index="high_impact_sector",
        columns="region_0",
        values="is_average_rate_below_trend",
    )
    .fillna(0)
)

total_nbr = (
    df_eq_emissions_adjusted.groupby(["region_0", "high_impact_sector"])["isin"]
    .count()
    .reset_index()
    .pivot(index="high_impact_sector", columns="region_0", values="isin")
    .fillna(0)
)

prop_eq_below_trend = (
    "'"
    + nbr_eq_below_trend.astype(int).astype(str)
    + "/"
    + total_nbr.astype(int).astype(str)
)

prop_float_eq_below_trend = (nbr_eq_below_trend / total_nbr).fillna(0)

df_eq_emissions_adjusted["is_average_rate_missing"] = df_eq_emissions_adjusted[
    "average_rate"
].isna()

nbr_eq_missing = (
    df_eq_emissions_adjusted.groupby(["region_0", "high_impact_sector"])[
        "is_average_rate_missing"
    ]
    .sum()
    .reset_index()
    .pivot(
        index="high_impact_sector", columns="region_0", values="is_average_rate_missing"
    )
    .fillna(0)
)

prop_eq_missing = (
    "'"
    + nbr_eq_missing.astype(int).astype(str)
    + "/"
    + total_nbr.astype(int).astype(str)
)

prop_float_eq_missing = nbr_eq_missing.div(total_nbr).fillna(0)

In [88]:
set(list(df_hist_trends['region'].unique())) - set(list(df['region_0'].unique()))

{'Emg Europe', 'Total'}

In [92]:
set(list(df['region_0'].unique())) - set(list(df_hist_trends['region'].unique()))

{'Emg EMEA'}

In [93]:
df_hist_trends[df_hist_trends['region']=='Emg Europe']

,region,high_impact_sector,average_trend_2021_2024,average_trend_2014_2024
11,Emg Europe,"Agriculture, forestry and fishing",0.010798,0.015844
24,Emg Europe,Airlines,0.149583,0.039848
37,Emg Europe,Aluminium,-0.007100,0.001350
50,Emg Europe,Automobiles,0.023050,0.019839
63,Emg Europe,Banking,0.007766,0.011156
76,Emg Europe,Cement,0.006803,0.023086
89,Emg Europe,Chemicals,-0.000190,0.010186
102,Emg Europe,Coal mining,0.007964,0.011888
115,Emg Europe,Consumer goods & services,0.003919,0.010102
128,Emg Europe,Diversified mining,-0.001199,0.005263
141,Emg Europe,Electric utilities,-0.008746,0.000488
154,Emg Europe,Food producers,0.009400,0.014620
167,Emg Europe,Industrials,-0.002836,0.004244
180,Emg Europe,non-HIMS,0.005615,0.009767
193,Emg Europe,Oil and gas,0.007544,0.005207
206,Emg Europe,Paper,-0.004978,0.002872
219,Emg Europe,Real estate,-0.006343,0.004982
232,Emg Europe,Shipping,0.023202,0.011530
245,Emg Europe,Steel,-0.006899,0.001455
258,Emg Europe,Transportation,0.007743,0.009851

In [94]:
df_hist_trends

,region,high_impact_sector,average_trend_2021_2024,average_trend_2014_2024
0,Dev America CA,"Agriculture, forestry and fishing",-0.003750,0.002096
1,Dev America US,"Agriculture, forestry and fishing",-0.003750,0.002096
2,Dev Asia-Pac JP,"Agriculture, forestry and fishing",-0.002877,-0.002802
3,Dev Asia-Pac Other,"Agriculture, forestry and fishing",0.009473,0.001148
4,Dev Europe EU,"Agriculture, forestry and fishing",-0.014528,-0.009450
...,...,...,...,...
255,Emg Asia-Pac CN,Transportation,0.023032,0.027937
256,Emg Asia-Pac IN,Transportation,0.052773,0.035628
257,Emg Asia-Pac Other,Transportation,0.023032,0.027937
258,Emg Europe,Transportation,0.007743,0.009851
259,Total,Transportation,0.014360,0.011120

In [101]:
df_average_trends = df_eq_emissions_adjusted.groupby(['region_0', 'high_impact_sector'])['average_rate'].mean().reset_index()

In [99]:
import matplotlib.pyplot as plt
import matplotlib as mpl

In [100]:
def plot_sector_region_heatmap(
    df,
    output_file,
    title="",
    reverse_colors=False,
    value_col="average_rate",
    region_col="region_0",
    sector_col="high_impact_sector",
    figsize=(12, 8),
):
    # Pivot
    table = df.pivot(
        index=sector_col,
        columns=region_col,
        values=value_col
    )

    data = table.values

    # Colormap
    cmap = mpl.colormaps["RdYlGn_r" if reverse_colors else "RdYlGn"].copy()
    cmap.set_bad(color="lightgrey")

    # Bornes symétriques autour de 0 pour bien gérer + / -
    vmax = np.nanmax(np.abs(data))
    vmin = -vmax if not np.isnan(vmax) else -1
    vmax = vmax if not np.isnan(vmax) else 1

    fig, ax = plt.subplots(figsize=figsize)

    im = ax.imshow(
        data,
        cmap=cmap,
        vmin=vmin,
        vmax=vmax,
        aspect="auto"
    )

    # Axes
    ax.set_xticks(range(len(table.columns)))
    ax.set_xticklabels(table.columns, rotation=45, ha="right")

    ax.set_yticks(range(len(table.index)))
    ax.set_yticklabels(table.index)

    # Format texte : +x.x% / -x.x%
    for i in range(table.shape[0]):
        for j in range(table.shape[1]):
            val = data[i, j]

            if np.isnan(val):
                txt = ""
            else:
                txt = f"{val:+.1f}%"

            ax.text(
                j, i, txt,
                ha="center", va="center",
                fontsize=8, color="black"
            )

    ax.set_title(title)
    plt.tight_layout()
    plt.savefig(output_file, dpi=300, bbox_inches="tight")
    plt.close()

In [ ]:
plot_sector_region_heatmap(df_average_trends, "output/regions_sectors_average_trend_em_adjusted.png", 
                           title="Average trends by region and sector of the average rate of the adjusted emissions" , reverse_colors=True)

In [ ]:
plot_sector_region_heatmap(df_average_trends[~(df_average_trends['high_impact_sector']=="Banking")], "output/regions_sectors_ex_bank_average_trend_em_adjusted.png",  
                           title="Average trends by region and sector (ex bank) of the average rate of the adjusted emissions", reverse_colors=True )

In [128]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib as mpl


def plot_sector_region_heatmap_with_totals(
    df,
    region_totals,
    sector_totals,
    output_file,
    title="",
    reverse_colors=False,
    value_col="average_rate",
    region_col="region_0",
    sector_col="high_impact_sector",
    figsize=(12, 8),
):
    # Tableau principal
    table = df.pivot(
        index=sector_col,
        columns=region_col,
        values=value_col
    )

    # Aligne les totaux sur les labels du pivot
    region_totals = region_totals.reindex(table.columns)
    sector_totals = sector_totals.reindex(table.index)

    # Ajoute la colonne Total (totaux par secteur)
    table["Total"] = sector_totals

    # Ajoute la ligne Total (totaux par région)
    table.loc["Total"] = list(region_totals) + [np.nan]

    data = table.values.astype(float)

    # Colormap
    cmap = mpl.colormaps["RdYlGn_r" if reverse_colors else "RdYlGn"].copy()
    cmap.set_bad(color="lightgrey")

    # Bornes symétriques autour de 0
    vmax = np.nanmax(np.abs(data))
    vmin = -vmax if not np.isnan(vmax) else -1
    vmax = vmax if not np.isnan(vmax) and vmax != 0 else 1

    fig, ax = plt.subplots(figsize=figsize)

    ax.imshow(
        data,
        cmap=cmap,
        vmin=vmin,
        vmax=vmax,
        aspect="auto"
    )
    n_rows, n_cols = table.shape

    # ligne verticale avant la colonne "Total"
    ax.axvline(x=n_cols - 1 - 0.5, color="black", linewidth=2)

    # ligne horizontale avant la ligne "Total"
    ax.axhline(y=n_rows - 1 - 0.5, color="black", linewidth=2)
    # Axes
    ax.set_xticks(range(len(table.columns)))
    ax.set_xticklabels(table.columns, rotation=45, ha="right")

    ax.set_yticks(range(len(table.index)))
    ax.set_yticklabels(table.index)

    # Texte
    for i in range(table.shape[0]):
        for j in range(table.shape[1]):
            val = data[i, j]
            txt = "" if np.isnan(val) else f"{val:+.1f}%"

            ax.text(
                j, i, txt,
                ha="center", va="center",
                fontsize=8, color="black"
            )

    ax.set_title(title)
    plt.tight_layout()
    plt.savefig(output_file, dpi=300, bbox_inches="tight")
    plt.close()

In [129]:
plot_sector_region_heatmap_with_totals(df_average_trends[~(df_average_trends['high_impact_sector']=="Banking")], "output/regions_sectors_ex_bank_average_trend_em_adjusted_with_total.png",  
                           title="Average trends by region and sector (ex bank) of the average rate of the adjusted emissions", reverse_colors=True )

TypeError: plot_sector_region_heatmap_with_totals() missing 2 required positional arguments: 'sector_totals' and 'output_file'

In [115]:
df_average_trends

           region_0         high_impact_sector  average_rate
0    Dev America CA                   Airlines      0.123430
1    Dev America CA                Automobiles      0.065246
2    Dev America CA                    Banking      0.716657
3    Dev America CA                  Chemicals      0.031353
4    Dev America CA  Consumer goods & services      0.052049
..              ...                        ...           ...
206        Emg EMEA                Real estate      1.719366
207        Emg EMEA                   Shipping      0.006159
208        Emg EMEA                      Steel      0.117183
209        Emg EMEA             Transportation     -0.259813
210        Emg EMEA                   non-HIMS     -0.029513

[211 rows x 3 columns]

In [130]:
df_eq_emissions_adjusted_ex_bank = df_eq_emissions_adjusted[~(df_eq_emissions_adjusted['high_impact_sector']=='Banking')]

df_average_trends = (
    df_eq_emissions_adjusted_ex_bank
    .groupby(['region_0', 'high_impact_sector'])['average_rate']
    .mean()
    .reset_index()
)

df_average_trends_regions = (
    df_eq_emissions_adjusted_ex_bank
    .groupby('region_0')['average_rate']
    .mean()
)

df_average_trends_sectors = (
    df_eq_emissions_adjusted_ex_bank
    .groupby('high_impact_sector')['average_rate']
    .mean()
)

plot_sector_region_heatmap_with_totals(
    df=df_average_trends,
    region_totals=df_average_trends_regions,
    sector_totals=df_average_trends_sectors,
    output_file="output/regions_sectors_ex_bank_average_trend_em_adjusted_with_total.png",  
                           title="Average trends by region and sector (ex bank) of the average rate of the adjusted emissions", reverse_colors=True )

In [118]:
df_eq_emissions_adjusted.groupby('region_0')['average_rate'].mean()

region_0
Dev America CA        9.043473e-02
Dev America US        6.638782e+00
Dev Asia-Pac JP       4.092556e-01
Dev Asia-Pac Other    2.678252e-01
Dev Europe EU         9.498305e+03
Dev Europe GB         5.296780e-01
Dev Europe Other      5.957586e+06
Emg America           5.274485e-01
Emg Asia-Pac CN       2.155212e-01
Emg Asia-Pac IN       3.537995e-01
Emg Asia-Pac Other    3.825755e-01
Emg EMEA              8.949278e-01
Name: average_rate, dtype: float64

In [121]:
df_average_trends.groupby('region_0')['average_rate'].mean()

region_0
Dev America CA        1.046432e-01
Dev America US        2.739762e+00
Dev Asia-Pac JP       2.096363e-01
Dev Asia-Pac Other    1.677449e-01
Dev Europe EU         5.375180e+03
Dev Europe GB         4.892911e-01
Dev Europe Other      3.598314e+06
Emg America           3.213525e-01
Emg Asia-Pac CN       1.115102e-01
Emg Asia-Pac IN       1.991192e-01
Emg Asia-Pac Other    2.088135e-01
Emg EMEA              2.865067e-01
Name: average_rate, dtype: float64

In [131]:
df_hist_trends

,region,high_impact_sector,average_trend_2021_2024,average_trend_2014_2024
0,Dev America CA,"Agriculture, forestry and fishing",-0.003750,0.002096
1,Dev America US,"Agriculture, forestry and fishing",-0.003750,0.002096
2,Dev Asia-Pac JP,"Agriculture, forestry and fishing",-0.002877,-0.002802
3,Dev Asia-Pac Other,"Agriculture, forestry and fishing",0.009473,0.001148
4,Dev Europe EU,"Agriculture, forestry and fishing",-0.014528,-0.009450
...,...,...,...,...
255,Emg Asia-Pac CN,Transportation,0.023032,0.027937
256,Emg Asia-Pac IN,Transportation,0.052773,0.035628
257,Emg Asia-Pac Other,Transportation,0.023032,0.027937
258,Emg Europe,Transportation,0.007743,0.009851
259,Total,Transportation,0.014360,0.011120

In [136]:
df_hist_trends

,region,high_impact_sector,average_trend_2021_2024,average_trend_2014_2024
0,Dev America CA,"Agriculture, forestry and fishing",-0.003750,0.002096
1,Dev America US,"Agriculture, forestry and fishing",-0.003750,0.002096
2,Dev Asia-Pac JP,"Agriculture, forestry and fishing",-0.002877,-0.002802
3,Dev Asia-Pac Other,"Agriculture, forestry and fishing",0.009473,0.001148
4,Dev Europe EU,"Agriculture, forestry and fishing",-0.014528,-0.009450
...,...,...,...,...
255,Emg Asia-Pac CN,Transportation,0.023032,0.027937
256,Emg Asia-Pac IN,Transportation,0.052773,0.035628
257,Emg Asia-Pac Other,Transportation,0.023032,0.027937
258,Emg Europe,Transportation,0.007743,0.009851
259,Total,Transportation,0.014360,0.011120

In [145]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib as mpl


def plot_sector_region_heatmap_with_totals_2(
    df,
    region_totals,
    sector_totals,
    totals,
    output_file,
    title="",
    reverse_colors=False,
    value_col="average_rate",
    region_col="region_0",
    sector_col="high_impact_sector",
    figsize=(12, 8),
):
    # Pivot principal
    table = df.pivot(
        index=sector_col,
        columns=region_col,
        values=value_col
    )

    # Alignement
    region_totals = region_totals.reindex(table.columns)
    sector_totals = sector_totals.reindex(table.index)

    # Ajout colonne Total
    table["Total"] = sector_totals

    # Ajout ligne Total
    total_row = pd.Series(index=table.columns, dtype=float)
    total_row.loc[region_totals.index] = region_totals.values
    total_row.loc["Total"] = totals   # ou df[value_col].mean()
    table.loc["Total"] = total_row

    data = table.values.astype(float)

    cmap = mpl.colormaps["RdYlGn_r" if reverse_colors else "RdYlGn"].copy()
    cmap.set_bad(color="lightgrey")

    vmax = np.nanmax(np.abs(data))
    vmin = -vmax if not np.isnan(vmax) else -1
    vmax = vmax if not np.isnan(vmax) and vmax != 0 else 1

    fig, ax = plt.subplots(figsize=figsize)

    ax.imshow(
        data,
        cmap=cmap,
        vmin=vmin,
        vmax=vmax,
        aspect="auto"
    )

    ax.set_xticks(range(len(table.columns)))
    ax.set_xticklabels(table.columns, rotation=45, ha="right")

    ax.set_yticks(range(len(table.index)))
    ax.set_yticklabels(table.index)

    for i in range(table.shape[0]):
        for j in range(table.shape[1]):
            val = data[i, j]
            txt = "" if np.isnan(val) else f"{val:+.1f}%"
            ax.text(j, i, txt, ha="center", va="center", fontsize=8, color="black")

    # séparation visuelle des totaux
    n_rows, n_cols = table.shape
    ax.axvline(x=n_cols - 1 - 0.5, color="black", linewidth=2)
    ax.axhline(y=n_rows - 1 - 0.5, color="black", linewidth=2)

    ax.set_title(title)
    plt.tight_layout()
    plt.savefig(output_file, dpi=300, bbox_inches="tight")
    plt.close()

In [150]:
# df_hist_trends = df_hist_trends[~(df_hist_trends['high_impact_sector']=='Banking')]
col_average_rate = "average_trend_2021_2024"
df_average_trends = (
    df_hist_trends.rename(columns={"region": "region_0", col_average_rate: "average_rate"})
    .groupby(['region_0', 'high_impact_sector'])['average_rate']
    .mean()
    .reset_index()
)

df_average_trends_regions = (
    df_hist_trends.rename(columns={"region": "region_0", col_average_rate: "average_rate"})
    .groupby('region_0')['average_rate']
    .mean()
)

df_average_trends_sectors = (
    df_hist_trends.rename(columns={"region": "region_0", col_average_rate: "average_rate"})
    .groupby('high_impact_sector')['average_rate']
    .mean()
)

average_trend_all = df_hist_trends[col_average_rate].mean()

plot_sector_region_heatmap_with_totals_2(
    df=df_average_trends,
    region_totals=df_average_trends_regions,
    sector_totals=df_average_trends_sectors,
    totals=average_trend_all,
    output_file="output/regions_sectors_hist_trend_with_total_21_24.png",  
                           title="Average hist trends btwn 2021 and 2024 by region and sector", reverse_colors=True )

In [149]:
# df_hist_trends = df_hist_trends[~(df_hist_trends['high_impact_sector']=='Banking')]
col_average_rate = "average_trend_2014_2024"
df_average_trends = (
    df_hist_trends.rename(columns={"region": "region_0", col_average_rate: "average_rate"})
    .groupby(['region_0', 'high_impact_sector'])['average_rate']
    .mean()
    .reset_index()
)

df_average_trends_regions = (
    df_hist_trends.rename(columns={"region": "region_0", col_average_rate: "average_rate"})
    .groupby('region_0')['average_rate']
    .mean()
)

df_average_trends_sectors = (
    df_hist_trends.rename(columns={"region": "region_0", col_average_rate: "average_rate"})
    .groupby('high_impact_sector')['average_rate']
    .mean()
)

average_trend_all = df_hist_trends[col_average_rate].mean()

plot_sector_region_heatmap_with_totals_2(
    df=df_average_trends,
    region_totals=df_average_trends_regions,
    sector_totals=df_average_trends_sectors,
    totals=average_trend_all,
    output_file="output/regions_sectors_hist_trend_with_total_14_24.png",  
                           title="Average hist trends btwn 2014 and 2024 by region and sector", reverse_colors=True )

In [ ]:
"average_trend_2021_2024"[-4:]
"average_trend_2021_2024"[-9:-5]

'2024'

In [153]:
"average_trend_2021_2024"[-9:-5]

'2021'